import feladatok
#feladatok.feladat1()
#feladatok.feladat2(1258920)
#feladatok.feladat3(324)
#feladatok.feladat4(0)
#feladatok.feladat5("hétfő","programozás")
#feladatok.feladat6()
#feladatok.feladat7()
#feladatok.feladatkiallitas()
#feladatok.feladat8()
#feladatok.feladat9()
#feladatok.feladat10()
#feladatok.feladat11()
feladatok.feladat12(12,24)
#feladatok.feladat13(4,6)